spring:
  application:
    name: api-gateway-okta
  config:
    import: 'optional:configserver:${config-server:http://192.168.1.17:9090/}'
  profiles:
    active: dev
  cloud:
    config:
      uri: '${config-server:http://192.168.1.17:9090/}'
      name: app-server,api-gateway-okta
