okta:
  oauth2:
    issuer: https://dev-31054060.okta.com/oauth2/default
spring:
  application:
    name: api-gateway-okta
  config:
    import: 'optional:configserver:http://192.168.1.31:9090'
  profiles:
    active: dev
